name: sahbi_flix
description: A Flutter movie app with authentication
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.10
  
  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Image
  image_picker: ^1.0.7
  image_picker_web: ^4.0.0
  cached_network_image: ^3.3.1
  
  # Video
  youtube_player_flutter: ^9.0.1

  # Utils
  intl: ^0.19.0

  # Navigation
  go_router: ^13.0.0
  
  # Forms & Validation
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
